name: PipelineFlask

on:
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest coverage  # Added coverage here
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Teste 
      run: coverage run app_test.py

    - name: Relatorio do teste
      run: coverage report -m

    - name: Render Deploy Action
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.SERVICEID }}
        api-key: ${{ secrets.APIKEY }}
